default:
  development: &common
    adapter: sqlite3
    username:
    password:
    database: happy_friday_development
    min_messages: WARNING
    reconnect: true
    pool: 5
    encoding: unicode
    host: localhost
  test:
    <<: *common
    database: happy_friday_test
  production:
    <<: *common
    database: happy_friday_production
